#!/bin/bash

BATT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)

CHARGE=$(xrdb -q | grep '*color5'| awk '{print $NF}')
GOOD=$(xrdb -q | grep '*color6'| awk '{print $NF}')
BAD=$(xrdb -q | grep '*color1'| awk '{print $NF}')

echo "$BATT%"

if [ $STATUS == "Charging" ]; then
    echo $CHARGE
elif [ $BATT -ge 20 ]; then
    echo $GOOD
else
    echo $BAD
fi
