#!/bin/bash

BATT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)

GREAT=$(xrdb -q | grep '*color2'| awk '{print $NF}')
GOOD=$(xrdb -q | grep '*color7'| awk '{print $NF}')
BAD=$(xrdb -q | grep '*color1'| awk '{print $NF}')

echo "$BATT%"
echo "$BATT%"

if [ $BATT -ge 90 ]; then
    echo $GREAT
elif [ $BATT -ge 20 ]; then
    echo $GOOD
else
    echo $BAD
fi
